### ISSUE TITLE
Bunch of errors when trying to build the solution

### ISSUE THREAD

**Issue by zix3r** [ama6nen/savedecrypter#1]
I'm getting a bunch of errors when trying to build the solution.
Tried fixing it, but with no luck.
I'll attach an image below.
![image](https://user-images.githubusercontent.com/43238887/79566719-b446cd00-80bb-11ea-8fb1-4399a7d85ec1.png)

**Comment by zix3r** [comment]
Fixed the pthread.h missing, but this pops up now.
![image](https://user-images.githubusercontent.com/43238887/79569667-b52e2d80-80c0-11ea-8735-8e321c24a6b8.png)

**Comment by RubbyGT** [comment]
> Fixed the pthread.h missing, but this pops up now.
> ![image](https://user-images.githubusercontent.com/43238887/79569667-b52e2d80-80c0-11ea-8735-8e321c24a6b8.png)

read them?

**Comment by zix3r** [comment]
sorry for not replying, been busy this past week
ive tried fixing it but with no luck, if you know what to do, could you please tell me?

**Comment by C-r-a-n-d-s** [comment]
thats easy to fix, just google lmfao..

**Comment by xSynapticV2** [comment]
yea if someone can help me with these errors please contact me on Discord xSynaptic#2846

**Comment by plex8968** [comment]
oh yeah, googling = key to success you fucking moron :)

**Comment by Crandetan** [comment]
#define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS 

Yes I am a moron, like totally. Btw I told you it is easy to fix, no needto worry about these abc wavey underscore stuff
